# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-24664cd8-35f6-49a8-939b-bc247b63ecea";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-24664cd8-35f6-49a8-939b-bc247b63ecea".device = "/dev/disk/by-uuid/24664cd8-35f6-49a8-939b-bc247b63ecea";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/85AB-A13F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/CF700" = {
    device = "/dev/disk/by-uuid/858452a3-3069-4dec-8c44-4cb908c5c128";
    fsType = "btrfs";
    options = [
      "user"
      "nofail"
      "rw"
      "exec"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/CF700 0777 root root -"
  ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2b2b436e-1e8f-4e0d-829d-058ecc4d13d0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
